
stdthread = {
    '1/4-20 UNC': {'Sub Type': 'Standard Thread', 'Size': 'M6x1', 'Nominal Diameter': 0.006 , 'Standard': 'ANSI Metric - PT', 'Internal Minor': 0.005, 'Pitch': 0.001}, #in inch change to mm equivalent.
    '5/16-18 UNC': {'Sub Type': 'Standard Thread', 'Size': 'M8x1.25', 'Nominal Diameter': 0.008, 'Standard': 'ANSI Metric - PT', 'Internal Minor': 0.068, 'Pitch': 0.00125},
    '3/8-16 UNC': {'Sub Type': 'Standard Thread', 'Size': 'M10x1.5', 'Nominal Diameter': 0.010, 'Standard': 'ANSI Metric - PT', 'Internal Minor': 0.085}, 'Pitch': 0.0015,
    '1/2-13 UNC': {'Sub Type': 'Standard Thread', 'Size': 'M12x1.75', 'Nominal Diameter': 0.012, 'Standard': 'ANSI Metric - PT', 'Internal Minor': 0.0102, 'Pitch': 0.00175},
    '5/8-18 UNC': {'Sub Type': 'Standard Thread', 'Size': 'M16x2', 'Nominal Diameter': 0.016, 'Standard': 'ANSI Metric - PT', 'Internal Minor': 0.014, 'Pitch': 0.002},
    '3/4-10 UNC': {'Sub Type': 'Standard Thread', 'Size': 'M20x2.5', 'Nominal Diameter': 0.020, 'Standard': 'ANSI Metric - PT', 'Internal Minor': 0.0175, 'Pitch': 0.0025},
}


drillsize = {
    #  0: {'Sub Type': 'Drill Size', 'Size': 0.35, 'Hole Diameter': '0.3500', 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  1: {'Sub Type': 'Drill Size', 'Size': 0.38, 'Hole Diameter': 0.3800, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  2: {'Sub Type': 'Drill Size', 'Size': 0.4, 'Hole Diameter': 0.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  3: {'Sub Type': 'Drill Size', 'Size': 0.42, 'Hole Diameter': 0.4200, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  4: {'Sub Type': 'Drill Size', 'Size': 0.45, 'Hole Diameter': 0.4500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  5: {'Sub Type': 'Drill Size', 'Size': 0.48, 'Hole Diameter': 0.4800, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  6: {'Sub Type': 'Drill Size', 'Size': 0.5, 'Hole Diameter': 0.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  7: {'Sub Type': 'Drill Size', 'Size': 0.55, 'Hole Diameter': 0.5500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  8: {'Sub Type': 'Drill Size', 'Size': 0.6, 'Hole Diameter': 0.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  9: {'Sub Type': 'Drill Size', 'Size': 0.65, 'Hole Diameter': 0.6500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  10: {'Sub Type': 'Drill Size', 'Size': 0.7, 'Hole Diameter': 0.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  11: {'Sub Type': 'Drill Size', 'Size': 0.75, 'Hole Diameter': 0.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  12: {'Sub Type': 'Drill Size', 'Size': 0.8, 'Hole Diameter': 0.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  13: {'Sub Type': 'Drill Size', 'Size': 0.85, 'Hole Diameter': 0.8500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  14: {'Sub Type': 'Drill Size', 'Size': 0.9, 'Hole Diameter': 0.9000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  15: {'Sub Type': 'Drill Size', 'Size': 0.95, 'Hole Diameter': 0.9500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  16: {'Sub Type': 'Drill Size', 'Size': 1, 'Hole Diameter': 1.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  17: {'Sub Type': 'Drill Size', 'Size': 1.05, 'Hole Diameter': 1.0500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  18: {'Sub Type': 'Drill Size', 'Size': 1.1, 'Hole Diameter': 1.1000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  19: {'Sub Type': 'Drill Size', 'Size': 1.15, 'Hole Diameter': 1.1500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  20: {'Sub Type': 'Drill Size', 'Size': 1.2, 'Hole Diameter': 1.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  21: {'Sub Type': 'Drill Size', 'Size': 1.25, 'Hole Diameter': 1.2500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  22: {'Sub Type': 'Drill Size', 'Size': 1.3, 'Hole Diameter': 1.3000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  23: {'Sub Type': 'Drill Size', 'Size': 1.35, 'Hole Diameter': 1.3500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  24: {'Sub Type': 'Drill Size', 'Size': 1.4, 'Hole Diameter': 1.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  25: {'Sub Type': 'Drill Size', 'Size': 1.45, 'Hole Diameter': 1.4500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  26: {'Sub Type': 'Drill Size', 'Size': 1.5, 'Hole Diameter': 1.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  27: {'Sub Type': 'Drill Size', 'Size': 1.55, 'Hole Diameter': 1.5500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  28: {'Sub Type': 'Drill Size', 'Size': 1.6, 'Hole Diameter': 1.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  29: {'Sub Type': 'Drill Size', 'Size': 1.65, 'Hole Diameter': 1.6500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  30: {'Sub Type': 'Drill Size', 'Size': 1.7, 'Hole Diameter': 1.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  31: {'Sub Type': 'Drill Size', 'Size': 1.75, 'Hole Diameter': 1.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  32: {'Sub Type': 'Drill Size', 'Size': 1.8, 'Hole Diameter': 1.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  33: {'Sub Type': 'Drill Size', 'Size': 1.85, 'Hole Diameter': 1.8500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  34: {'Sub Type': 'Drill Size', 'Size': 1.9, 'Hole Diameter': 1.9000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  35: {'Sub Type': 'Drill Size', 'Size': 1.95, 'Hole Diameter': 1.9500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  36: {'Sub Type': 'Drill Size', 'Size': 2, 'Hole Diameter': 2.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  37: {'Sub Type': 'Drill Size', 'Size': 2.05, 'Hole Diameter': 2.0500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  38: {'Sub Type': 'Drill Size', 'Size': 2.1, 'Hole Diameter': 2.1000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  39: {'Sub Type': 'Drill Size', 'Size': 2.15, 'Hole Diameter': 2.1500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  40: {'Sub Type': 'Drill Size', 'Size': 2.2, 'Hole Diameter': 2.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  41: {'Sub Type': 'Drill Size', 'Size': 2.25, 'Hole Diameter': 2.2500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  42: {'Sub Type': 'Drill Size', 'Size': 2.3, 'Hole Diameter': 2.3000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  43: {'Sub Type': 'Drill Size', 'Size': 2.35, 'Hole Diameter': 2.3500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  44: {'Sub Type': 'Drill Size', 'Size': 2.4, 'Hole Diameter': 2.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  45: {'Sub Type': 'Drill Size', 'Size': 2.45, 'Hole Diameter': 2.4500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  46: {'Sub Type': 'Drill Size', 'Size': 2.5, 'Hole Diameter': 2.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  47: {'Sub Type': 'Drill Size', 'Size': 2.55, 'Hole Diameter': 2.5500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  48: {'Sub Type': 'Drill Size', 'Size': 2.6, 'Hole Diameter': 2.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  49: {'Sub Type': 'Drill Size', 'Size': 2.65, 'Hole Diameter': 2.6500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  50: {'Sub Type': 'Drill Size', 'Size': 2.7, 'Hole Diameter': 2.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  51: {'Sub Type': 'Drill Size', 'Size': 2.75, 'Hole Diameter': 2.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  52: {'Sub Type': 'Drill Size', 'Size': 2.8, 'Hole Diameter': 2.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  53: {'Sub Type': 'Drill Size', 'Size': 2.9, 'Hole Diameter': 2.9000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  54: {'Sub Type': 'Drill Size', 'Size': 3, 'Hole Diameter': 3.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  55: {'Sub Type': 'Drill Size', 'Size': 3.1, 'Hole Diameter': 3.1000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  56: {'Sub Type': 'Drill Size', 'Size': 3.2, 'Hole Diameter': 3.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  57: {'Sub Type': 'Drill Size', 'Size': 3.25, 'Hole Diameter': 3.2500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  58: {'Sub Type': 'Drill Size', 'Size': 3.3, 'Hole Diameter': 3.3000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  59: {'Sub Type': 'Drill Size', 'Size': 3.4, 'Hole Diameter': 3.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  60: {'Sub Type': 'Drill Size', 'Size': 3.5, 'Hole Diameter': 3.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  61: {'Sub Type': 'Drill Size', 'Size': 3.6, 'Hole Diameter': 3.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  62: {'Sub Type': 'Drill Size', 'Size': 3.7, 'Hole Diameter': 3.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  63: {'Sub Type': 'Drill Size', 'Size': 3.75, 'Hole Diameter': 3.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  64: {'Sub Type': 'Drill Size', 'Size': 3.8, 'Hole Diameter': 3.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  65: {'Sub Type': 'Drill Size', 'Size': 3.9, 'Hole Diameter': 3.9000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  66: {'Sub Type': 'Drill Size', 'Size': 4, 'Hole Diameter': 4.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  67: {'Sub Type': 'Drill Size', 'Size': 4.1, 'Hole Diameter': 4.1000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  68: {'Sub Type': 'Drill Size', 'Size': 4.2, 'Hole Diameter': 4.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  69: {'Sub Type': 'Drill Size', 'Size': 4.25, 'Hole Diameter': 4.2500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  70: {'Sub Type': 'Drill Size', 'Size': 4.3, 'Hole Diameter': 4.3000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  71: {'Sub Type': 'Drill Size', 'Size': 4.4, 'Hole Diameter': 4.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  72: {'Sub Type': 'Drill Size', 'Size': 4.5, 'Hole Diameter': 4.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  73: {'Sub Type': 'Drill Size', 'Size': 4.6, 'Hole Diameter': 4.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  74: {'Sub Type': 'Drill Size', 'Size': 4.7, 'Hole Diameter': 4.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  75: {'Sub Type': 'Drill Size', 'Size': 4.75, 'Hole Diameter': 4.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  76: {'Sub Type': 'Drill Size', 'Size': 4.8, 'Hole Diameter': 4.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  77: {'Sub Type': 'Drill Size', 'Size': 4.9, 'Hole Diameter': 4.9000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  78: {'Sub Type': 'Drill Size', 'Size': 5, 'Hole Diameter': 5.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  79: {'Sub Type': 'Drill Size', 'Size': 5.1, 'Hole Diameter': 5.1000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  80: {'Sub Type': 'Drill Size', 'Size': 5.2, 'Hole Diameter': 5.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  81: {'Sub Type': 'Drill Size', 'Size': 5.25, 'Hole Diameter': 5.2500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  82: {'Sub Type': 'Drill Size', 'Size': 5.3, 'Hole Diameter': 5.3000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  83: {'Sub Type': 'Drill Size', 'Size': 5.4, 'Hole Diameter': 5.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  84: {'Sub Type': 'Drill Size', 'Size': 5.5, 'Hole Diameter': 5.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  85: {'Sub Type': 'Drill Size', 'Size': 5.6, 'Hole Diameter': 5.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  86: {'Sub Type': 'Drill Size', 'Size': 5.7, 'Hole Diameter': 5.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  87: {'Sub Type': 'Drill Size', 'Size': 5.75, 'Hole Diameter': 5.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  88: {'Sub Type': 'Drill Size', 'Size': 5.8, 'Hole Diameter': 5.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  89: {'Sub Type': 'Drill Size', 'Size': 5.9, 'Hole Diameter': 5.9000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  90: {'Sub Type': 'Drill Size', 'Size': 6, 'Hole Diameter': 6.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  91: {'Sub Type': 'Drill Size', 'Size': 6.1, 'Hole Diameter': 6.1000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  92: {'Sub Type': 'Drill Size', 'Size': 6.2, 'Hole Diameter': 6.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  93: {'Sub Type': 'Drill Size', 'Size': 6.25, 'Hole Diameter': 6.2500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    '1/4': {'Sub Type': 'Drill Size', 'Size': 6.3, 'Hole Diameter': 6.3000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  95: {'Sub Type': 'Drill Size', 'Size': 6.4, 'Hole Diameter': 6.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  96: {'Sub Type': 'Drill Size', 'Size': 6.5, 'Hole Diameter': 6.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  97: {'Sub Type': 'Drill Size', 'Size': 6.6, 'Hole Diameter': 6.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  98: {'Sub Type': 'Drill Size', 'Size': 6.7, 'Hole Diameter': 6.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  99: {'Sub Type': 'Drill Size', 'Size': 6.75, 'Hole Diameter': 6.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  100: {'Sub Type': 'Drill Size', 'Size': 6.8, 'Hole Diameter': 6.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  101: {'Sub Type': 'Drill Size', 'Size': 6.9, 'Hole Diameter': 6.9000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  102: {'Sub Type': 'Drill Size', 'Size': 7, 'Hole Diameter': 7.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    '9/32': {'Sub Type': 'Drill Size', 'Size': 7.1, 'Hole Diameter': 7.1000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  104: {'Sub Type': 'Drill Size', 'Size': 7.2, 'Hole Diameter': 7.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  105: {'Sub Type': 'Drill Size', 'Size': 7.25, 'Hole Diameter': 7.2500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  106: {'Sub Type': 'Drill Size', 'Size': 7.3, 'Hole Diameter': 7.3000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  107: {'Sub Type': 'Drill Size', 'Size': 7.4, 'Hole Diameter': 7.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  108: {'Sub Type': 'Drill Size', 'Size': 7.5, 'Hole Diameter': 7.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  109: {'Sub Type': 'Drill Size', 'Size': 7.6, 'Hole Diameter': 7.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  110: {'Sub Type': 'Drill Size', 'Size': 7.7, 'Hole Diameter': 7.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  111: {'Sub Type': 'Drill Size', 'Size': 7.75, 'Hole Diameter': 7.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  112: {'Sub Type': 'Drill Size', 'Size': 7.8, 'Hole Diameter': 7.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  113: {'Sub Type': 'Drill Size', 'Size': 7.9, 'Hole Diameter': 7.9000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  114: {'Sub Type': 'Drill Size', 'Size': 8, 'Hole Diameter': 8.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  115: {'Sub Type': 'Drill Size', 'Size': 8.1, 'Hole Diameter': 8.1000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  116: {'Sub Type': 'Drill Size', 'Size': 8.2, 'Hole Diameter': 8.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  117: {'Sub Type': 'Drill Size', 'Size': 8.25, 'Hole Diameter': 8.2500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  118: {'Sub Type': 'Drill Size', 'Size': 8.3, 'Hole Diameter': 8.3000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  119: {'Sub Type': 'Drill Size', 'Size': 8.4, 'Hole Diameter': 8.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  120: {'Sub Type': 'Drill Size', 'Size': 8.5, 'Hole Diameter': 8.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  121: {'Sub Type': 'Drill Size', 'Size': 8.6, 'Hole Diameter': 8.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  122: {'Sub Type': 'Drill Size', 'Size': 8.7, 'Hole Diameter': 8.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  123: {'Sub Type': 'Drill Size', 'Size': 8.75, 'Hole Diameter': 8.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  124: {'Sub Type': 'Drill Size', 'Size': 8.8, 'Hole Diameter': 8.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  125: {'Sub Type': 'Drill Size', 'Size': 8.9, 'Hole Diameter': 8.9000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  126: {'Sub Type': 'Drill Size', 'Size': 9, 'Hole Diameter': 9.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  127: {'Sub Type': 'Drill Size', 'Size': 9.1, 'Hole Diameter': 9.1000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  128: {'Sub Type': 'Drill Size', 'Size': 9.2, 'Hole Diameter': 9.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  129: {'Sub Type': 'Drill Size', 'Size': 9.25, 'Hole Diameter': 9.2500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  'DZM3/8': {'Sub Type': 'Drill Size', 'Size': 9.3, 'Hole Diameter': 9.3000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  131: {'Sub Type': 'Drill Size', 'Size': 9.4, 'Hole Diameter': 9.4000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    '3/8': {'Sub Type': 'Drill Size', 'Size': 9.5, 'Hole Diameter': 9.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  133: {'Sub Type': 'Drill Size', 'Size': 9.6, 'Hole Diameter': 9.6000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  134: {'Sub Type': 'Drill Size', 'Size': 9.7, 'Hole Diameter': 9.7000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  135: {'Sub Type': 'Drill Size', 'Size': 9.75, 'Hole Diameter': 9.7500, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  136: {'Sub Type': 'Drill Size', 'Size': 10, 'Hole Diameter': '0.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    '13/32': {'Sub Type': 'Drill Size', 'Size': 10.2, 'Hole Diameter': 0.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  138: {'Sub Type': 'Drill Size', 'Size': 10.5, 'Hole Diameter': 0.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  139: {'Sub Type': 'Drill Size', 'Size': 10.8, 'Hole Diameter': 0.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  140: {'Sub Type': 'Drill Size', 'Size': 11, 'Hole Diameter': 1.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  141: {'Sub Type': 'Drill Size', 'Size': 11.2, 'Hole Diameter': 1.2000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  142: {'Sub Type': 'Drill Size', 'Size': 11.5, 'Hole Diameter': 1.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  143: {'Sub Type': 'Drill Size', 'Size': 11.8, 'Hole Diameter': 1.8000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  144: {'Sub Type': 'Drill Size', 'Size': 12, 'Hole Diameter': 2.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    '1/2': {'Sub Type': 'Drill Size', 'Size': 12.5, 'Hole Diameter': 2.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  146: {'Sub Type': 'Drill Size', 'Size': 13, 'Hole Diameter': 3.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  147: {'Sub Type': 'Drill Size', 'Size': 13.5, 'Hole Diameter': 3.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  148: {'Sub Type': 'Drill Size', 'Size': 14, 'Hole Diameter': 4.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  149: {'Sub Type': 'Drill Size', 'Size': 14.5, 'Hole Diameter': 4.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  150: {'Sub Type': 'Drill Size', 'Size': 15, 'Hole Diameter': 5.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  151: {'Sub Type': 'Drill Size', 'Size': 15.5, 'Hole Diameter': 5.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  152: {'Sub Type': 'Drill Size', 'Size': 16, 'Hole Diameter': 6.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  153: {'Sub Type': 'Drill Size', 'Size': 17, 'Hole Diameter': 7.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  154: {'Sub Type': 'Drill Size', 'Size': 17.5, 'Hole Diameter': 7.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  155: {'Sub Type': 'Drill Size', 'Size': 18, 'Hole Diameter': 8.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  156: {'Sub Type': 'Drill Size', 'Size': 18.5, 'Hole Diameter': 8.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  157: {'Sub Type': 'Drill Size', 'Size': 19, 'Hole Diameter': 9.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  158: {'Sub Type': 'Drill Size', 'Size': 20, 'Hole Diameter': 0.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  159: {'Sub Type': 'Drill Size', 'Size': 20.5, 'Hole Diameter': 0.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  160: {'Sub Type': 'Drill Size', 'Size': 21, 'Hole Diameter': 1.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  161: {'Sub Type': 'Drill Size', 'Size': 21.5, 'Hole Diameter': 1.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  162: {'Sub Type': 'Drill Size', 'Size': 22, 'Hole Diameter': 2.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  163: {'Sub Type': 'Drill Size', 'Size': 22.5, 'Hole Diameter': 2.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  164: {'Sub Type': 'Drill Size', 'Size': 23, 'Hole Diameter': 3.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  165: {'Sub Type': 'Drill Size', 'Size': 23.5, 'Hole Diameter': 3.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  166: {'Sub Type': 'Drill Size', 'Size': 24, 'Hole Diameter': 4.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  167: {'Sub Type': 'Drill Size', 'Size': 24.5, 'Hole Diameter': 4.5000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  168: {'Sub Type': 'Drill Size', 'Size': 25, 'Hole Diameter': 5.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
    #  169: {'Sub Type': 'Drill Size', 'Size': 26, 'Hole Diameter': 6.0000, 'Standard': 'ANSI Metric - PT', 'Fit': 'Exact'},
}



